### ISSUE TITLE
Fix the app crash on start due to toast implementation in RoomsFragment

### ISSUE THREAD

**Issue by krnblni** [coding-blocks/Chatter#117]
**Actual Behaviour**

- Crash on start.

**Expected Behaviour**

- Fetch and display available rooms.

**Steps to reproduce it**

- Build and start the app.

**LogCat for the issue**

- 07-21 00:32:23.304 11904-11947/com.codingblocks.chatter E/AndroidRuntime: FATAL EXCEPTION: Thread-4
    Process: com.codingblocks.chatter, PID: 11904
    java.lang.RuntimeException: Can't toast on a thread that has not called Looper.prepare()
        at android.widget.Toast$TN.<init>(Toast.java:393)
        at android.widget.Toast.<init>(Toast.java:117)
        at android.widget.Toast.makeText(Toast.java:280)
        at android.widget.Toast.makeText(Toast.java:270)
        at com.codingblocks.chatter.RoomsFragment$3$1.run(RoomsFragment.java:241)
        at java.lang.Thread.run(Thread.java:764)

- 07-21 00:32:23.304 11904-11948/com.codingblocks.chatter E/AndroidRuntime: FATAL EXCEPTION: Thread-5
    Process: com.codingblocks.chatter, PID: 11904
    java.lang.RuntimeException: Can't toast on a thread that has not called Looper.prepare()
        at android.widget.Toast$TN.<init>(Toast.java:393)
        at android.widget.Toast.<init>(Toast.java:117)
        at android.widget.Toast.makeText(Toast.java:280)
        at android.widget.Toast.makeText(Toast.java:270)
        at com.codingblocks.chatter.RoomsFragment$3$1.run(RoomsFragment.java:241)
        at java.lang.Thread.run(Thread.java:764)

**Screenshots of the issue**

- N/A

**Expected Bounty**

- Tagged in the issue.

**Comment by firefinchdev** [comment]
Possible Fix #118

**Comment by championswimmer** [comment]
@firefinchdev go ahead and claim the bounty! I didn't merge your PR as it is, but cherrypicked it into the refactor
