### ISSUE TITLE
App crash when selecting Rooms in bottom navigation bar

### ISSUE THREAD

**Issue by 28Ritu** [coding-blocks/Chatter#26]
The app crashes when a user selects the Rooms tab in the bottom navigation bar.

**Loogcat For The Error**

05-15 10:20:38.243 7526-7526/com.codingblocks.chatter E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.codingblocks.chatter, PID: 7526
                                                                        java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.RecyclerView.setLayoutManager(android.support.v7.widget.RecyclerView$LayoutManager)' on a null object reference
                                                                            at com.codingblocks.chatter.RoomsFragment.onCreateView(RoomsFragment.java:71)
                                                                            at android.support.v4.app.Fragment.performCreateView(Fragment.java:2248)
                                                                            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1340)
                                                                            at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1569)
                                                                            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1636)
                                                                            at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
                                                                            at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2415)
                                                                            at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2201)
                                                                            at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2155)
                                                                            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2064)
                                                                            at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:718)
                                                                            at android.os.Handler.handleCallback(Handler.java:815)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                            at android.os.Looper.loop(Looper.java:207)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5728)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
05-15 10:20:38.980 7526-7542/com.codingblocks.chatter E/NativeCrypto: ssl=0xb9bd9e98 cert_verify_callback x509_store_ctx=0xa3dfac7c arg=0x0
05-15 10:20:38.980 7526-7542/com.codingblocks.chatter E/NativeCrypto: ssl=0xb9bd9e98 cert_verify_callback calling verifyCertificateChain authMethod=ECDHE_RSA

I would like to work on this issue.

**Comment by 28Ritu** [comment]
@championswimmer Kindly review this.

**Comment by arya-ayush** [comment]
I have fixed this issue locally. Please let me know how I have to create a pull request for it. Do I need to create my own branch on remote ?

**Comment by aggarwalpulkit596** [comment]
@championswimmer bhaiya this issues and #27 both of them are still there so can i make pull request for them ?

**Comment by championswimmer** [comment]
sure

**Comment by aggarwalpulkit596** [comment]
Not an issue anymore therefore it should be closed.

**Comment by venomousboxer** [comment]
App is crashing on selecting room button in bottom navigation bar everytime I run it on device with API level 25 or less. Can someone please confirm this issue

**Comment by aggarwalpulkit596** [comment]
it has been fixed in #97 so not an issue anymore @venomousboxer
