### ISSUE TITLE
App crash upon traversing through all the buttons in the bottom nav bar

### ISSUE THREAD

**Issue by 28Ritu** [coding-blocks/Chatter#27]
When the user first selects the Rooms tab, it works fine. (I am working on the issue #26 ) . But after frequent and continuous traversal of all the tabs, the app crashes.

**Logcat**
05-15 10:35:48.092 8971-8989/com.codingblocks.chatter E/NativeCrypto: ssl=0xb9bd2bd0 cert_verify_callback x509_store_ctx=0xa3dfac7c arg=0x0
05-15 10:35:48.092 8971-8989/com.codingblocks.chatter E/NativeCrypto: ssl=0xb9bd2bd0 cert_verify_callback calling verifyCertificateChain authMethod=ECDHE_RSA
05-15 10:35:54.618 8971-9092/com.codingblocks.chatter E/NativeCrypto: ssl=0xb9c26de8 cert_verify_callback x509_store_ctx=0xa2d9cc7c arg=0x0
05-15 10:35:54.618 8971-9092/com.codingblocks.chatter E/NativeCrypto: ssl=0xb9c26de8 cert_verify_callback calling verifyCertificateChain authMethod=ECDHE_RSA
05-15 10:35:54.822 8971-9094/com.codingblocks.chatter E/NativeCrypto: ssl=0xb9c10408 cert_verify_callback x509_store_ctx=0xa2c97c7c arg=0x0
05-15 10:35:54.822 8971-9094/com.codingblocks.chatter E/NativeCrypto: ssl=0xb9c10408 cert_verify_callback calling verifyCertificateChain authMethod=ECDHE_RSA
05-15 10:35:54.879 8971-9103/com.codingblocks.chatter E/NativeCrypto: ssl=0xb9bb4e48 cert_verify_callback x509_store_ctx=0xa28dcc7c arg=0x0
05-15 10:35:54.880 8971-9103/com.codingblocks.chatter E/NativeCrypto: ssl=0xb9bb4e48 cert_verify_callback calling verifyCertificateChain authMethod=ECDHE_RSA
05-15 10:35:54.897 8971-9102/com.codingblocks.chatter E/NativeCrypto: ssl=0xb9bb4d08 cert_verify_callback x509_store_ctx=0xa29e1c7c arg=0x0
05-15 10:35:54.897 8971-9102/com.codingblocks.chatter E/NativeCrypto: ssl=0xb9bb4d08 cert_verify_callback calling verifyCertificateChain authMethod=ECDHE_RSA
05-15 10:35:55.259 8971-9092/com.codingblocks.chatter E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
                                                                        Process: com.codingblocks.chatter, PID: 8971
                                                                        java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.app.FragmentActivity.runOnUiThread(java.lang.Runnable)' on a null object reference
                                                                            at com.codingblocks.chatter.RoomsFragment$2.onResponse(RoomsFragment.java:133)
                                                                            at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
                                                                            at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                            at java.lang.Thread.run(Thread.java:818)

I would like to work on this issue.

**Comment by 28Ritu** [comment]
@championswimmer Kindly review this.

**Comment by aggarwalpulkit596** [comment]
Not an issue anymore therefore it should be closed.
