### ISSUE TITLE
Chatter Application unable to start. It shows 'authenticationWebView' was not found

### ISSUE THREAD

**Issue by RishabhRawatAndroid** [coding-blocks/Chatter#59]
**Device Use : Redmi Note 3**

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.codingblocks.chatter/com.codingblocks.chatter.AuthenticationActivity}: java.lang.IllegalStateException: Required view 'authentication_web_view' with ID 2131230747 for field 'authenticationWebView' was not found. If this view is optional add '@Nullable' (fields) or '@Optional' (methods) annotation.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2455)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2515)
        at android.app.ActivityThread.access$1000(ActivityThread.java:154)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1379)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5571)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
     Caused by: java.lang.IllegalStateException: Required view 'authentication_web_view' with ID 2131230747 for field 'authenticationWebView' was not found. If this view is optional add '@Nullable' (fields) or '@Optional' (methods) annotation.
        at butterknife.internal.Utils.findRequiredView(Utils.java:92)
        at butterknife.internal.Utils.findRequiredViewAsType(Utils.java:104)
        at com.codingblocks.chatter.AuthenticationActivity_ViewBinding.<init>(AuthenticationActivity_ViewBinding.java:25)
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at butterknife.ButterKnife.createBinding(ButterKnife.java:199)
        at butterknife.ButterKnife.bind(ButterKnife.java:124)
        at com.codingblocks.chatter.AuthenticationActivity.onCreate(AuthenticationActivity.java:39)
        at android.app.Activity.performCreate(Activity.java:6357)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2408)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2515) 
        at android.app.ActivityThread.access$1000(ActivityThread.java:154) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1379) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:157) 
        at android.app.ActivityThread.main(ActivityThread.java:5571) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635) 
```

**Comment by RishabhRawatAndroid** [comment]
## Android Version 6.0 Marshmallow

![20180518_202104](https://user-images.githubusercontent.com/26416942/40241818-96fce4be-5ad9-11e8-810d-fc6d64ad35fe.gif)
