### ISSUE TITLE
App Crashing on Selecting a room

### ISSUE THREAD

**Issue by aggarwalpulkit596** [coding-blocks/Chatter#75]
**Actual Behaviour**
On selecting a room app is crashing with error
Invalid query: field 'roomId' not found in table 'RoomsTable'.

**Expected Behaviour**

It should display a list of messages
**Steps to reproduce it**

Just select any of the room from rooms fragment

**LogCat for the issue**

05-25 09:41:52.504 30729-30729/com.codingblocks.chatter E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.codingblocks.chatter, PID: 30729
    java.lang.IllegalArgumentException: Invalid query: field 'roomId' not found in table 'RoomsTable'.
        at io.realm.internal.fields.CachedFieldDescriptor.compileFieldDescription(CachedFieldDescriptor.java:78)
        at io.realm.internal.fields.FieldDescriptor.compileIfNecessary(FieldDescriptor.java:284)
        at io.realm.internal.fields.FieldDescriptor.getColumnIndices(FieldDescriptor.java:177)
        at io.realm.RealmQuery.equalToWithoutThreadValidation(RealmQuery.java:256)
        at io.realm.RealmQuery.equalTo(RealmQuery.java:251)
        at io.realm.RealmQuery.equalTo(RealmQuery.java:236)
        at com.codingblocks.chatter.RoomFragment.onCreateView(RoomFragment.java:78)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2354)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6798)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
**Screenshots of the issue**

Where-ever possible add a screenshot of the issue.

**Expected Bounty**

20

**Comment by aggarwalpulkit596** [comment]
@championswimmer bhaiya kindly look into the issues and assign bounties to them so that we can work further 
lot of issues in chatter app
![screen shot 2018-05-27 at 10 57 39 am](https://user-images.githubusercontent.com/29139786/40582779-70e43690-619d-11e8-88ed-9cab549aad55.png)
![screen shot 2018-05-27 at 10 39 39 am](https://user-images.githubusercontent.com/29139786/40582780-7145bcd0-619d-11e8-9fe5-095feb202042.png)
